[config]
schemaVersion = "0.0.1"

[package]
namespace = "Atopy"
name = "QuickPing"
versionNumber = "1.5.0"
description = "Ping what you see and pin it on the map !"
websiteUrl = "https://github.com/Vodianoi/QuickPingMod"
containsNsfwContent = false
dependencies = {  }

[build]
icon = "Package/icon.png"
readme = "Package/README.md"
outdir = "./build"

[[build.copy]]
source = "Package/plugins/QuickPing.dll"
target = "QuickPing.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]
categories = ["client-side","tools","tweaks","mods"]
